[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "myman"
version = "0.0.9"
description = "Draw from Sequence of 'My Man' Posts by Kevin Kruse"
authors = [
    { name = "Dirk Eddelbuettel", email = "edd@debian.org" }
]
requires-python = ">= 3.8"
readme = "README.md"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
mypackage = ["data/*"] 

#[dependency-groups]
#dev = [
#    "pytest>=8.3.5",
#]

[project.optional-dependencies]
test = ["pytest>=7.0"]
